### ISSUE TITLE
Create new version for packaging purposes

### ISSUE THREAD

**Issue by ivankovnatsky** [flosell/iam-policy-json-to-terraform#64]
Hello, can you please bump a version so we could update it nixpkgs here: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/tools/misc/iam-policy-json-to-terraform/default.nix#L5.

Thanks,
Ivan.

**Comment by flosell** [comment]
Hi @ivankovnatsky, thanks for reminding me :) Lots of work since the last release went into the web version of the tool that is deployed continuously so I guess I forgot to cut a new release and update the release notes. 

Fixed now, new version [1.8.1](https://github.com/flosell/iam-policy-json-to-terraform/releases/tag/1.8.1) is out now. 

Also, feel free to submit a PR to the [release script](https://github.com/flosell/iam-policy-json-to-terraform/blob/master/scripts/release.sh) if you want me to bump the nixpkg along with other packages.
